/* SEO global — siteUrl = URL pública atual; productionSiteUrl = domínio final no go-live */
window.ANTONOV_SEO = {
  siteUrl: 'https://www.antonovcenter.com.br',
  productionSiteUrl: 'https://www.antonovcenter.com.br',
  siteName: 'Antonov Center',
  locale: 'pt_BR',
  defaultImage: '/assets/foto-hero.png',
  business: {
    name: 'Antonov Center',
    legalName: 'Antonov Center LTDA',
    taxID: '62.421.964/0001-60',
    street: 'Av. 1º de Janeiro',
    city: 'Irecê',
    region: 'BA',
    postalCode: '44860-201',
    country: 'BR',
    phone: '+5574999631507',
    email: 'antonovacademia@gmail.com',
    lat: -11.3089689,
    lng: -41.853495,
    hours: ['Mo-Fr 05:00-23:00', 'Sa 06:00-15:00', 'Su 08:00-14:00'],
    operatingHours: {
      timezone: 'America/Bahia',
      weekday: { open: [5, 0], close: [23, 0] },
      saturday: { open: [6, 0], close: [15, 0] },
      sundayAndHoliday: { open: [8, 0], close: [14, 0] },
    },
    instagram: 'https://www.instagram.com/antonovcenter',
    mapsUrl: 'https://maps.app.goo.gl/rbhgwPvZnJfMyKkB9',
    areaServed: ['Irecê', 'Bahia', 'Brasil'],
    priceRange: 'R$ 169,90 a R$ 189,90',
  },
};
